/*
╔══════════════════════════════════════════════════════════════╗
║                         BLOXD FORGE                          ║
║                                                                ║
║                     Copyright © 2026                          ║
║                         _Xenon_                                ║
║                                                                ║
║               Recipe Forging With Forge Limits               ║
╚══════════════════════════════════════════════════════════════╝
*/

import{KVStore}from"./KVStore"
import{ItemRules}from"./Itemrules"

const C={accent:"#ff8c42",text:"#f2f4f7",muted:"#8b95a1",bad:"#ff5c5c"}
const ROMAN=["","I","II","III","IV","V","VI","VII","VIII","IX","X","XI","XII","XIII","XIV","XV","XVI","XVII","XVIII","XIX","XX","XXI","XXII","XXIII","XXIV","XXV","XXVI","XXVII","XXVIII","XXIX","The number after 29."]
const toRoman=(n)=>typeof n==="number"&&n>=1&&n<=10&&n%1===0?ROMAN[n]:String(n)
const prettyLabel=(s)=>{let out=String(s).replace(/([a-z0-9])([A-Z])/g,"$1 $2").replace(/[_-]+/g," ");return out.charAt(0).toUpperCase()+out.slice(1)}
const formatStatValue=(value)=>{if(value===null||value===undefined)return"";if(typeof value==="boolean")return value?"Yes":"No";if(typeof value==="object"){let parts=[];for(let k in value)parts.push(prettyLabel(k)+" "+formatStatValue(value[k]));return parts.join(" / ")}return String(value)}
const txt=(str,color,bold)=>{let style={};if(color)style.color=color;if(bold)style.fontWeight="bold";return{str,style}}
const ico=(icon,color)=>color?{icon,style:{color}}:{icon}
const itemLabel=(r)=>r.displayName||r.base
const chanceTotal=(results)=>{let total=0;for(let res of results)total+=res.chance||1;return total}
const rollResult=(results)=>{let roll=Math.random()*chanceTotal(results);for(let res of results){roll-=res.chance||1;if(roll<=0)return res}return results[results.length-1]}
const collectItemStats=(r)=>{let stats=[],seen={};let push=(label,value,isEnch)=>{let key=String(label).toLowerCase();if(key==="forged"||key==="castid"||seen[key])return;seen[key]=true;stats.push({label:prettyLabel(label),value,isEnch:isEnch===true})};if(r.enchantments)for(let k in r.enchantments)push(k,toRoman(r.enchantments[k]),true);let attrs=r.customAttributes||{};for(let a in attrs){if(a==="enchantments"){let ce=attrs[a]||{};for(let ek in ce)push(ek,toRoman(ce[ek]),true)}else if(a==="enchantmentTier"){push("Tier",toRoman(attrs[a]),false)}else{push(a,formatStatValue(attrs[a]),false)}}if(r.enchantmentTier)push("Tier",toRoman(r.enchantmentTier),false);return stats}
const tierRedundant=(st)=>st.label==="Tier"&&/^tier\b/i.test(String(st.value))
const statText=(st)=>tierRedundant(st)?String(st.value):st.label+" "+st.value
const statsToString=(r)=>collectItemStats(r).map(statText).join(" \u2022 ")
const sendRecipePreview=(pid,results)=>{let total=chanceTotal(results);for(let res of results){let pct=total>0?Math.round(((res.chance||1)/total)*1000)/10:100;for(let r of res.items){let head=[ico(r.base),txt(" "+itemLabel(r),C.text,true)];if((r.amount||1)>1)head.push(txt(" x"+r.amount,C.muted));if(results.length>1)head.push(txt("  "+pct+"%",C.accent,true));api.sendMessage(pid,head);if(r.description)api.sendMessage(pid,[txt("  "+r.description,C.muted)]);let line=[txt("  ")];collectItemStats(r).forEach((st,i)=>{if(i>0)line.push(txt("  \u2022  ",C.muted));if(!tierRedundant(st))line.push(txt(st.label+" ",C.muted));line.push(txt(String(st.value),C.text))});if(line.length>1)api.sendMessage(pid,line)}}}
const validateRecipe=(recipe)=>{if(!recipe||typeof recipe!=="object"){api.log("[Forge] forge() expected a recipe object but got "+typeof recipe+". Pass { cost: [...], results: [...] }.");return false}if(!Array.isArray(recipe.cost)){api.log("[Forge] recipe.cost must be an array but got "+typeof recipe.cost+". Use cost: [] for a free recipe: "+JSON.stringify(recipe));return false}let results=recipe.results;if(!results||results.length===0){api.log("[forge] recipe has no results, aborting: "+JSON.stringify(recipe));return false}for(let i=0;i<results.length;i++){if(!results[i].items||results[i].items.length===0){api.log("[forge] result entry "+i+" has no items, aborting: "+JSON.stringify(recipe));return false}}return true}
const deny=(pid,icon,color,label,text)=>api.sendMessage(pid,[ico(icon,color),txt(" "),txt(label,C.text,true),txt(text,color)])
const hasSpace=(pid,results)=>{let need=0;for(let res of results)need=Math.max(need,res.items.length);let free=api.getInventoryFreeSlotCount(pid);if(free>=need)return true;let short=need-free;api.sendMessage(pid,[ico("fa-solid fa-box-open",C.bad),txt(" Inventory full",C.text,true),txt("  free up "+short+" slot"+(short===1?"":"s")+" to forge",C.muted)]);return false}
const readForgeLimit=(forgeKey,defaultLimit)=>{let key="forge:limit:"+forgeKey,data=KVStore.get(key);if(data!=null)return{ready:true,limit:data.remaining};if(defaultLimit==null)return{ready:true,limit:null};if(KVStore.set(key,{remaining:defaultLimit})===false)return{ready:false,limit:null};return{ready:true,limit:defaultLimit}}
const scanMatch=(entry)=>{let spec={name:entry.name};if(entry.displayName)spec["attributes.customDisplayName"]=entry.displayName;if(entry.description)spec["attributes.customDescription"]=entry.description;if(entry.enchantments)for(let k in entry.enchantments)spec["attributes.customAttributes.enchantments."+k]=entry.enchantments[k];return ItemRules.test(spec)}
const readSlots=(pid)=>{let slots=[];for(let s=0;s<=50;s++){let item=api.getItemSlot(pid,s);if(item)slots.push({idx:s,item})}return slots}
const checkCost=(pid,normalCost,scanCost)=>{let missing=[],scanMatches=[];for(let c of normalCost){let have=api.getInventoryItemAmount(pid,c.name);if(have<c.amount)missing.push({name:c.name,displayName:c.displayName||null,shortage:c.amount-have})}let slots=scanCost.length>0?readSlots(pid):[];for(let entry of scanCost){let matches=scanMatch(entry),found=[],count=0;for(let s=0;s<slots.length&&count<entry.amount;s++){let sl=slots[s];if(!matches(sl.item))continue;found.push(sl.idx);count+=sl.item.amount||1;slots.splice(s,1);s--}if(count<entry.amount){missing.push({name:entry.name,displayName:entry.displayName||null,shortage:entry.amount-count})}else{scanMatches.push({name:entry.name,amount:entry.amount,slots:found})}}return{missing,scanMatches}}
const sendMissing=(pid,missing,forgeLimit)=>{api.sendMessage(pid,[ico("fa-solid fa-triangle-exclamation",C.bad),txt(" Missing materials",C.text,true)]);missing.forEach((m,i)=>{let branch=i===missing.length-1?"\u2514 ":"\u251c ";api.sendMessage(pid,[txt("  "+branch,C.muted),ico(m.name),txt(" "+(m.displayName||m.name),C.text),txt("  x"+m.shortage,C.bad,true)])});if(forgeLimit!=null)api.sendMessage(pid,[txt("  "+forgeLimit+" forge"+(forgeLimit===1?"":"s")+" remaining",C.muted)])}
const consumeScans=(pid,pname,scanMatches)=>{for(let match of scanMatches){let toRemove=match.amount;for(let idx of match.slots){if(toRemove<=0)break;let sl=api.getItemSlot(pid,idx);if(!sl||sl.name!==match.name){api.log("[forge] scan slot mismatch for "+pname+" at idx "+idx+", aborting forge before any items given");api.sendMessage(pid,[ico("fa-solid fa-triangle-exclamation",C.bad),txt(" Inventory changed mid-forge, please try again.",C.bad)]);return false}let inSlot=sl.amount||1;if(inSlot>toRemove){api.setItemSlot(pid,idx,sl.name,inSlot-toRemove,sl.attributes);toRemove=0}else{api.setItemSlot(pid,idx,"Air",null);toRemove-=inSlot}}}return true}
const genCastId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,10)
const registerCast=(castId,base,pname)=>KVStore.set("cast:"+castId,{item:base,player:pname,forgedAt:Date.now()})
const giveResults=(pid,items,pname,trackDupes)=>{for(let r of items){let enchantments=Object.assign({},r.enchantments),attrs=Object.assign({},r.customAttributes);attrs.enchantments=enchantments;if(r.enchantmentTier)attrs.enchantmentTier=r.enchantmentTier;attrs.forged=true;if(trackDupes){attrs.castId=genCastId();registerCast(attrs.castId,r.base,pname)}api.giveItem(pid,r.base,r.amount,{customDisplayName:r.displayName||undefined,customDescription:r.description||undefined,customAttributes:attrs})}}
const announceForge=(pid,pname,items)=>{let msg=[ico("fa-solid fa-hammer",C.accent),txt(" "+pname,C.text,true),txt(" forged ",C.muted)];items.forEach((r,i)=>{msg.push(ico(r.base));msg.push(txt(" "+itemLabel(r),C.text,true));if((r.amount||1)>1)msg.push(txt(" x"+r.amount,C.text,true));let statStr=statsToString(r);if(statStr){msg.push(txt("  - ",C.muted));msg.push(txt(statStr,C.muted))}if(i<items.length-1)msg.push(txt("  +  ",C.muted))});api.broadcastMessage(msg);api.sendFlyingMiddleMessage(pid,[ico("fa-solid fa-hammer",C.accent),txt(" "+itemLabel(items[0]),C.text,true),txt(" forged!",C.muted)],0,4000);api.playSound(pid,"exp_levelup",1,1)}
const forge=(pid,recipe)=>{if(!validateRecipe(recipe))return false;let{cost,results}=recipe,forgeKey=recipe.forgeKey||null;let preview=()=>sendRecipePreview(pid,results);let pname=api.getEntityName(pid);let free=Forge.admins.indexOf(pname)!==-1&&api.getClientOption(pid,"creative")===true;let firstLabel=itemLabel(results[0].items[0]);if(recipe.available===false&&!free){preview();deny(pid,"fa-solid fa-ban",C.bad,firstLabel," is not available at this time.");return false}let forgeLimit=null;if(forgeKey!=null){let lim=readForgeLimit(forgeKey,recipe.forgeLimit);if(!lim.ready){deny(pid,"fa-solid fa-hourglass-half",C.accent,firstLabel," is not ready yet, try again in a moment.");return false}forgeLimit=lim.limit;if(forgeLimit!=null&&forgeLimit<=0&&!free){preview();deny(pid,"fa-solid fa-clock",C.accent,firstLabel," has no more forges remaining.");return false}}if(!free){let normalCost=cost.filter((c)=>!c.customScan),scanCost=cost.filter((c)=>c.customScan);let{missing,scanMatches}=checkCost(pid,normalCost,scanCost);if(missing.length>0){preview();sendMissing(pid,missing,forgeLimit);return false}if(!hasSpace(pid,results))return false;if(!consumeScans(pid,pname,scanMatches))return false;for(let c of normalCost)api.removeItemName(pid,c.name,c.amount);if(forgeKey!=null&&forgeLimit!=null)KVStore.set("forge:limit:"+forgeKey,{remaining:forgeLimit-1})}else if(!hasSpace(pid,results)){return false}let items=rollResult(results).items;giveResults(pid,items,pname,recipe.trackDupes===true);announceForge(pid,pname,items);return true}
const scanCasts=(pid,out)=>{for(let s=0;s<=50;s++){let item=api.getItemSlot(pid,s);let castId=item&&item.attributes&&item.attributes.customAttributes&&item.attributes.customAttributes.castId;if(castId)(out[castId]||(out[castId]=[])).push({player:pid,where:"inventory",slot:s})}let moonstone=api.getMoonstoneChestItems(pid)||[];moonstone.forEach((item,idx)=>{let castId=item&&item.attributes&&item.attributes.customAttributes&&item.attributes.customAttributes.castId;if(castId)(out[castId]||(out[castId]=[])).push({player:pid,where:"moonstoneChest",slot:idx})})}
const checkDupes=()=>{let seen={};for(let pid of api.getPlayerIds())scanCasts(pid,seen);let dupes=[],unregistered=[];for(let castId in seen){let locations=seen[castId];if(locations.length>1)dupes.push({castId,locations});if(KVStore.get("cast:"+castId)==null)unregistered.push({castId,locations})}return{dupes,unregistered}}

export let Forge={admins:[],setAdmins:(names)=>{if(!Array.isArray(names)){api.log("[Forge] setAdmins expected an array of player names but got "+typeof names+". Pass e.g. Forge.setAdmins([\"Name1\", \"Name2\"]).");return false}Forge.admins=names;return true},forge,checkDupes}
