/*
╔══════════════════════════════════════════════════════════════╗
║                          ITEM RULES                          ║
║                                                              ║
║         Rule Based Item Matching And Transformation          ║
╚══════════════════════════════════════════════════════════════╝
*/

const RULE_KEYS=["id","match","do","chain","once"],CONFIG_KEYS=["firstSlot","lastSlot","tellClient"],ROOTS=["name","amount","attributes"],BAD_SEGS=["__proto__","constructor","prototype"]
const USE_ENCH="Use keys like 'attributes.customAttributes.enchantments.<Enchant>' or a function match (item, ctx) => boolean.",USE_CUSTOM="Use keys like 'attributes.customAttributes.<Key>' or a function match (item, ctx) => boolean.",USE_FN="Use a function match (item, ctx) => boolean."
const OLD_MATCH:any={display:"Use the key 'attributes.customDisplayName'.",description:"Use the key 'attributes.customDescription'.",tier:"Use the key 'attributes.customAttributes.enchantmentTier'.",enchants:USE_ENCH,exactEnchants:USE_ENCH,hasEnchant:USE_ENCH,noEnchants:USE_FN,custom:USE_CUSTOM,exactCustom:USE_CUSTOM,hasCustom:USE_CUSTOM,noCustom:USE_FN,extra:"Use keys like 'attributes.<Key>'.",test:USE_FN}
const cfg:any={firstSlot:0,lastSlot:50,tellClient:true},rules:any[]=[],ids:any={},logged:any={}

function logOnce(key:string,msg:string):void{if(logged[key])return;logged[key]=true;api.log(msg)}
const has=(o:any,k:string):boolean=>Object.prototype.hasOwnProperty.call(o,k)
const isObj=(x:any):boolean=>x!==null&&typeof x==="object"
const plain=(re:any):any=>/[gy]/.test(re.flags)?new RegExp(re.source,re.flags.replace(/[gy]/g,"")):re
const dc=(x:any):any=>JSON.parse(JSON.stringify(x))
const errText=(e:any):string=>e instanceof Error?e.message:String(e)
const cloneItem=(i:any):any=>({name:i.name,amount:i.amount==null?null:i.amount,attributes:dc(i.attributes||{})})

function deepEq(a:any,b:any):boolean{if(a===b)return true;if(!isObj(a)||!isObj(b)||Array.isArray(a)!==Array.isArray(b))return false;let ka=Object.keys(a);if(ka.length!==Object.keys(b).length)return false;for(let k of ka)if(!has(b,k)||!deepEq(a[k],b[k]))return false;return true}
function same(a:any,b:any):boolean{return a.name===b.name&&(a.amount==null?null:a.amount)===(b.amount==null?null:b.amount)&&deepEq(a.attributes||{},b.attributes||{})}
function segs(path:string):string[]{let parts=String(path).split(".");for(let p of parts)if(p===""||BAD_SEGS.indexOf(p)!==-1)throw new Error("invalid path '"+path+"'. Use dotted keys like attributes.customDisplayName with no empty parts.");return parts}
function readSegs(obj:any,parts:string[]):any{let o=obj;for(let p of parts){if(!isObj(o)||!has(o,p))return undefined;o=o[p]}return o}
function testValue(m:any,value:any,item:any):any{if(Array.isArray(m)){for(let x of m){let r=testValue(x,value,item);if(r)return r}return null}if(typeof m==="function")return m(value,item)?[]:null;if(m===null)return value==null?[]:null;if(m===true)return value==null?null:[];if(value==null)return null;if(m instanceof RegExp)return plain(m).exec(String(value));return value===m?[]:null}

function compileMatch(spec:any,bad:any):any{if(typeof spec==="function")return(item:any,ctx:any)=>{let r=spec(item,ctx);return r?(r===true?{}:r):null};if(typeof spec==="string"||spec instanceof RegExp)return(item:any)=>{let r=testValue(spec,item.name,item);return r?{name:r}:null};if(Array.isArray(spec)){if(spec.length===0)bad("has an empty match list. Give it at least one name, regex, object or function.");let subs=spec.map((s:any)=>compileMatch(s,bad));return(item:any,ctx:any)=>{for(let f of subs){let r=f(item,ctx);if(r)return r}return null}}if(!isObj(spec))bad("has a match of type "+typeof spec+". Use a name, regex, function, list, or an object of paths.");let keys=Object.keys(spec);if(keys.length===0)bad("has an empty match object. Add a path such as name or attributes.customDisplayName.");let checks:any[]=keys.map((k:string)=>{if(has(OLD_MATCH,k))bad("uses match key '"+k+"' which was removed. "+OLD_MATCH[k]);let parts:string[]=[];try{parts=segs(k)}catch(e){bad("has a bad match key: "+errText(e))}if(ROOTS.indexOf(parts[0])===-1)bad("has match key '"+k+"' which must start with name, amount or attributes, for example attributes.customDisplayName.");if(spec[k]===undefined)bad("has match key '"+k+"' set to undefined. Use null to require it absent, true to require it present, or a value, regex or function.");return[k,parts,spec[k]]});return(item:any)=>{let info:any={};for(let c of checks){let r=testValue(c[2],readSegs(item,c[1]),item);if(!r)return null;info[c[0]]=r}return info}}

function nameHint(spec:any):string[]|null{if(typeof spec==="string")return[spec];if(Array.isArray(spec))return spec.every((s:any)=>typeof s==="string")?spec:null;if(isObj(spec)&&!(spec instanceof RegExp)&&typeof spec.name==="string")return[spec.name];return null}
function stampList(item:any):string[]{let c=isObj(item.attributes)?item.attributes.customAttributes:null;return isObj(c)&&Array.isArray(c.appliedRules)?c.appliedRules:[]}
function stamp(item:any,id:string):void{if(!isObj(item.attributes.customAttributes))item.attributes.customAttributes={};let c=item.attributes.customAttributes;if(!Array.isArray(c.appliedRules))c.appliedRules=[];c.appliedRules.push(id)}
function fail(rule:any,slot:any,index:number,where:string,e:any):void{logOnce("err:"+rule.label+":"+where,"[ItemRules] rule "+rule.label+" "+where+" threw on "+slot.name+" in slot "+index+": "+errText(e)+". Rules get (item, ctx): item is the raw { name, amount, attributes } and ctx.m holds match results. Enchants live at item.attributes.customAttributes.enchantments.")}

function add(rule:{id?:string;match:string|object|((item:any,ctx:any)=>any)|{[path:string]:string|number|boolean|null|object|((value:any,item:any)=>any)};do:((item:any,ctx:any)=>any)|((item:any,ctx:any)=>any)[];chain?:boolean;once?:boolean|string}):any{let label=isObj(rule)&&rule.id!==undefined?String(rule.id):"#"+rules.length;let bad=(msg:string):void=>{throw new Error("ItemRules: rule "+label+" "+msg)};if(!isObj(rule)||Array.isArray(rule))throw new Error("ItemRules: rule "+label+" must be an object like { match: /Sword$/, do: (item, ctx) => {...} }, found "+(Array.isArray(rule)?"a list":typeof rule)+". Use addAll for lists.");for(let k of Object.keys(rule))if(RULE_KEYS.indexOf(k)===-1)bad("has unknown key '"+k+"'. Valid keys: "+RULE_KEYS.join(", ")+".");if(rule.match===undefined)bad("needs a match, for example match: /^Diamond/ or match: (item, ctx) => boolean.");if(rule.do===undefined)bad("needs a do function, for example do: (item, ctx) => { item.name = \"New\"; }.");let actions:any[]=Array.isArray(rule.do)?rule.do:[rule.do];if(actions.length===0||!actions.every((f:any)=>typeof f==="function"))bad("do must be a function (item, ctx) => {...} or a list of them, found "+(Array.isArray(rule.do)?(rule.do.length===0?"an empty list":"a list with a non-function entry"):typeof rule.do)+".");if(rule.once===true&&rule.id===undefined)bad("uses once: true but has no id. Give the rule an id or set once to a string.");if(rule.once!==undefined&&rule.once!==true&&typeof rule.once!=="string")bad("once must be true or a string id, found "+typeof rule.once+".");if(rule.id!==undefined&&has(ids,String(rule.id)))bad("uses an id that is already taken. Ids must be unique because once stamps items with them.");let compiled:any={label,test:compileMatch(rule.match,bad),names:nameHint(rule.match),actions,chain:rule.chain===true,once:rule.once===true?String(rule.id):rule.once||undefined};if(rule.id!==undefined)ids[String(rule.id)]=true;rules.push(compiled);return compiled}

function apply(slot:any,playerId:any,index:number):any{let matched:string[]=[],item=slot;for(let rule of rules){if(rule.names&&rule.names.indexOf(item.name)===-1)continue;if(rule.once&&stampList(item).indexOf(rule.once)!==-1)continue;let ctx:any={playerId,slot:index,rule:rule.label,m:{}},found:any;try{found=rule.test(item,ctx)}catch(e){fail(rule,slot,index,"match",e);continue}if(!found)continue;ctx.m=found;let work=cloneItem(item);if(rule.once)stamp(work,rule.once);try{for(let fn of rule.actions)fn(work,ctx)}catch(e){fail(rule,slot,index,"do",e);continue}item=work;matched.push(rule.label);if(item.name==="Air"||!rule.chain)break}if(matched.length===0)return{changed:false,removed:false,matched};if(item.name==="Air")return{changed:true,removed:true,matched};let out={name:item.name,amount:item.amount==null?null:item.amount,attributes:item.attributes||{}};return{changed:!same(slot,out),removed:false,name:out.name,amount:out.amount,attributes:out.attributes,matched}}

function scan(playerId:any,firstSlot?:number,lastSlot?:number):number{let first=firstSlot===undefined?cfg.firstSlot:firstSlot,last=lastSlot===undefined?cfg.lastSlot:lastSlot,n=0;for(let idx=first;idx<=last;idx++){let slot:any=api.getItemSlot(playerId,idx);if(!slot)continue;let r=apply(slot,playerId,idx);if(!r.changed)continue;if(r.removed)api.setItemSlot(playerId,idx,"Air",null,{},cfg.tellClient);else api.setItemSlot(playerId,idx,r.name,r.amount,r.attributes,cfg.tellClient);n++}return n}

function config(opts:any):any{if(!isObj(opts)||Array.isArray(opts))throw new Error("ItemRules: config expects an object like { firstSlot: 0, lastSlot: 50, tellClient: true }, found "+(Array.isArray(opts)?"a list":typeof opts)+".");if(opts.ignoreEnchants!==undefined)throw new Error("ItemRules: config ignoreEnchants was removed because rules now see the raw item. Test an enchant with a path key such as \"attributes.customAttributes.enchantments.Forged\": null (null means absent) inside match, and remove ignoreEnchants from your config call.");for(let k of Object.keys(opts))if(CONFIG_KEYS.indexOf(k)===-1)throw new Error("ItemRules: config has unknown key '"+k+"'. Valid keys: "+CONFIG_KEYS.join(", ")+".");for(let k of["firstSlot","lastSlot"]){if(opts[k]===undefined)continue;if(typeof opts[k]!=="number")throw new Error("ItemRules: config "+k+" must be a number, found "+typeof opts[k]+".");cfg[k]=opts[k]}if(opts.tellClient!==undefined)cfg.tellClient=!!opts.tellClient;return Object.assign({},cfg)}

export let ItemRules={config,add,addAll:(list:any[]):any[]=>list.map((r:any)=>add(r)),clear:():void=>{rules.length=0;for(let k of Object.keys(ids))delete ids[k]},list:():string[]=>rules.map((r:any)=>r.label),apply,scan,run:scan}
