/*
╔══════════════════════════════════════════════════════════════╗
║                   BLOXD MATHLIB GEOMETRY                     ║
║                                                                ║
║                     Copyright © 2026                          ║
║                         _Xenon_                                ║
║                                                                ║
╚══════════════════════════════════════════════════════════════╝
*/
import{MathLib}from"./MathLib"
import{MathLibLinear}from"./MathLibLinear"
export let MathLibGeometry={
    aabbOverlap:(minA,maxA,minB,maxB)=>minA[0]<=maxB[0]&&maxA[0]>=minB[0]&&minA[1]<=maxB[1]&&maxA[1]>=minB[1]&&minA[2]<=maxB[2]&&maxA[2]>=minB[2],
    aabbContainsPoint:(min,max,p)=>p[0]>=min[0]&&p[0]<=max[0]&&p[1]>=min[1]&&p[1]<=max[1]&&p[2]>=min[2]&&p[2]<=max[2],
    aabbExpand:(min,max,amount)=>[[min[0]-amount,min[1]-amount,min[2]-amount],[max[0]+amount,max[1]+amount,max[2]+amount]],
    aabbMerge:(minA,maxA,minB,maxB)=>[[Math.min(minA[0],minB[0]),Math.min(minA[1],minB[1]),Math.min(minA[2],minB[2])],[Math.max(maxA[0],maxB[0]),Math.max(maxA[1],maxB[1]),Math.max(maxA[2],maxB[2])]],
    closestPointAABB:(p,min,max)=>[MathLib.clamp(p[0],min[0],max[0]),MathLib.clamp(p[1],min[1],max[1]),MathLib.clamp(p[2],min[2],max[2])],
    rayAABB:(origin,dir,min,max)=>{let tmin=-Infinity,tmax=Infinity;for(let i=0;i<3;i++){if(Math.abs(dir[i])<MathLib.EPS){if(origin[i]<min[i]||origin[i]>max[i])return null}else{let inv=1/dir[i],t1=(min[i]-origin[i])*inv,t2=(max[i]-origin[i])*inv;if(t1>t2){let tmp=t1;t1=t2;t2=tmp}tmin=Math.max(tmin,t1);tmax=Math.min(tmax,t2);if(tmin>tmax)return null}}return tmin<0?(tmax<0?null:tmax):tmin},
    sphereOverlap:(centerA,rA,centerB,rB)=>MathLib.distance2(centerA,centerB)<=(rA+rB)*(rA+rB),
    sphereAABBOverlap:(center,r,min,max)=>{let cp=MathLibGeometry.closestPointAABB(center,min,max);return MathLib.distance2(center,cp)<=r*r},
    pointInSphere:(p,center,r)=>MathLib.distance2(p,center)<=r*r,
    raySphere:(origin,dir,center,r)=>{let oc=MathLib.sub(origin,center),b=MathLib.dot(oc,dir),c=MathLib.dot(oc,oc)-r*r,disc=b*b-c;if(disc<0)return null;let sq=Math.sqrt(disc),t1=-b-sq,t2=-b+sq;if(t1>=0)return t1;if(t2>=0)return t2;return null},
    circleOverlap2D:(centerA,rA,centerB,rB)=>{let dx=centerB[0]-centerA[0],dz=centerB[1]-centerA[1];return dx*dx+dz*dz<=(rA+rB)*(rA+rB)},
    pointInCircle2D:(p,center,r)=>{let dx=p[0]-center[0],dz=p[1]-center[1];return dx*dx+dz*dz<=r*r},
    closestPointOnSegment2D:(p,a,b)=>{let ab=[b[0]-a[0],b[1]-a[1]],len2=ab[0]*ab[0]+ab[1]*ab[1],t=len2<MathLib.EPS?0:MathLib.clamp(((p[0]-a[0])*ab[0]+(p[1]-a[1])*ab[1])/len2,0,1);return[a[0]+ab[0]*t,a[1]+ab[1]*t]},
    circleLineIntersect2D:(center,r,a,b)=>{let d=[b[0]-a[0],b[1]-a[1]],f=[a[0]-center[0],a[1]-center[1]],aa=d[0]*d[0]+d[1]*d[1],bb=2*(f[0]*d[0]+f[1]*d[1]),cc=f[0]*f[0]+f[1]*f[1]-r*r,disc=bb*bb-4*aa*cc;if(disc<0)return null;disc=Math.sqrt(disc);let t1=(-bb-disc)/(2*aa),t2=(-bb+disc)/(2*aa),hits=[];if(t1>=0&&t1<=1)hits.push(t1);if(t2>=0&&t2<=1)hits.push(t2);return hits.length?hits:null},
    circlePolygonOverlap2D:(center,r,points)=>{if(MathLibGeometry.pointInPolygon2D(center,points))return true;for(let i=0;i<points.length;i++){let a=points[i],b=points[(i+1)%points.length],cp=MathLibGeometry.closestPointOnSegment2D(center,a,b),dx=center[0]-cp[0],dz=center[1]-cp[1];if(dx*dx+dz*dz<=r*r)return true}return false},
    obbAxes:box=>{let m=MathLibLinear.quatToMat3(box.orientation);return[[m[0],m[3],m[6]],[m[1],m[4],m[7]],[m[2],m[5],m[8]]]},
    worldToLocalOBB:(box,p)=>{let axes=MathLibGeometry.obbAxes(box),rel=MathLib.sub(p,box.center);return[MathLib.dot(rel,axes[0]),MathLib.dot(rel,axes[1]),MathLib.dot(rel,axes[2])]},
    pointInOBB:(p,box)=>{let l=MathLibGeometry.worldToLocalOBB(box,p);return Math.abs(l[0])<=box.halfExtents[0]&&Math.abs(l[1])<=box.halfExtents[1]&&Math.abs(l[2])<=box.halfExtents[2]},
    rayOBB:(origin,dir,box)=>{let axes=MathLibGeometry.obbAxes(box),localOrigin=MathLibGeometry.worldToLocalOBB(box,origin),localDir=[MathLib.dot(dir,axes[0]),MathLib.dot(dir,axes[1]),MathLib.dot(dir,axes[2])],min=[-box.halfExtents[0],-box.halfExtents[1],-box.halfExtents[2]];return MathLibGeometry.rayAABB(localOrigin,localDir,min,box.halfExtents)},
    obbOverlap:(a,b)=>{let axesA=MathLibGeometry.obbAxes(a),axesB=MathLibGeometry.obbAxes(b),axes=[axesA[0],axesA[1],axesA[2],axesB[0],axesB[1],axesB[2]];for(let i=0;i<3;i++)for(let j=0;j<3;j++){let c=MathLib.cross(axesA[i],axesB[j]);if(MathLib.length2(c)>MathLib.EPS)axes.push(MathLib.normalize(c))}let t=MathLib.sub(b.center,a.center);for(let i=0;i<axes.length;i++){let axis=axes[i],ra=Math.abs(MathLib.dot(axesA[0],axis))*a.halfExtents[0]+Math.abs(MathLib.dot(axesA[1],axis))*a.halfExtents[1]+Math.abs(MathLib.dot(axesA[2],axis))*a.halfExtents[2],rb=Math.abs(MathLib.dot(axesB[0],axis))*b.halfExtents[0]+Math.abs(MathLib.dot(axesB[1],axis))*b.halfExtents[1]+Math.abs(MathLib.dot(axesB[2],axis))*b.halfExtents[2],dist=Math.abs(MathLib.dot(t,axis));if(dist>ra+rb)return false}return true},
    closestPointOnSegment:(p,a,b)=>{let ab=MathLib.sub(b,a),len2=MathLib.length2(ab),t=len2<MathLib.EPS?0:MathLib.clamp(MathLib.dot(MathLib.sub(p,a),ab)/len2,0,1);return MathLib.add(a,MathLib.mul(ab,t))},
    segmentSegmentClosest:(p1,q1,p2,q2)=>{let d1=MathLib.sub(q1,p1),d2=MathLib.sub(q2,p2),r=MathLib.sub(p1,p2),a=MathLib.dot(d1,d1),e=MathLib.dot(d2,d2),f=MathLib.dot(d2,r),s,t;if(a<MathLib.EPS&&e<MathLib.EPS)return{pointA:p1,pointB:p2};if(a<MathLib.EPS){s=0;t=MathLib.clamp(f/e,0,1)}else{let c=MathLib.dot(d1,r);if(e<MathLib.EPS){t=0;s=MathLib.clamp(-c/a,0,1)}else{let b=MathLib.dot(d1,d2),denom=a*e-b*b;s=Math.abs(denom)>MathLib.EPS?MathLib.clamp((b*f-c*e)/denom,0,1):0;t=(b*s+f)/e;if(t<0){t=0;s=MathLib.clamp(-c/a,0,1)}else if(t>1){t=1;s=MathLib.clamp((b-c)/a,0,1)}}}return{pointA:MathLib.add(p1,MathLib.mul(d1,s)),pointB:MathLib.add(p2,MathLib.mul(d2,t))}},
    segmentPlaneIntersect:(a,b,planePoint,normal)=>{let d=MathLib.sub(b,a),denom=MathLib.dot(normal,d);if(Math.abs(denom)<MathLib.EPS)return null;let t=MathLib.dot(MathLib.sub(planePoint,a),normal)/denom;return t<0||t>1?null:MathLib.add(a,MathLib.mul(d,t))},
    distancePointLine:(p,linePoint,lineDir)=>{let dir=MathLib.normalize(lineDir),v=MathLib.sub(p,linePoint),t=MathLib.dot(v,dir),proj=MathLib.add(linePoint,MathLib.mul(dir,t));return MathLib.distance(p,proj)},
    triangleNormal:(a,b,c)=>MathLib.normalize(MathLib.cross(MathLib.sub(b,a),MathLib.sub(c,a))),
    triangleArea:(a,b,c)=>MathLib.length(MathLib.cross(MathLib.sub(b,a),MathLib.sub(c,a)))*0.5,
    triangleCentroid:(a,b,c)=>[(a[0]+b[0]+c[0])/3,(a[1]+b[1]+c[1])/3,(a[2]+b[2]+c[2])/3],
    barycentric:(p,a,b,c)=>{let v0=MathLib.sub(b,a),v1=MathLib.sub(c,a),v2=MathLib.sub(p,a),d00=MathLib.dot(v0,v0),d01=MathLib.dot(v0,v1),d11=MathLib.dot(v1,v1),d20=MathLib.dot(v2,v0),d21=MathLib.dot(v2,v1),denom=d00*d11-d01*d01;if(Math.abs(denom)<MathLib.EPS)return[1,0,0];let v=(d11*d20-d01*d21)/denom,w=(d00*d21-d01*d20)/denom,u=1-v-w;return[u,v,w]},
    pointInTriangle:(p,a,b,c)=>{let bc=MathLibGeometry.barycentric(p,a,b,c);return bc[0]>=-MathLib.EPS&&bc[1]>=-MathLib.EPS&&bc[2]>=-MathLib.EPS},
    closestPointOnTriangle:(p,a,b,c)=>{let ab=MathLib.sub(b,a),ac=MathLib.sub(c,a),ap=MathLib.sub(p,a),d1=MathLib.dot(ab,ap),d2=MathLib.dot(ac,ap);if(d1<=0&&d2<=0)return a;let bp=MathLib.sub(p,b),d3=MathLib.dot(ab,bp),d4=MathLib.dot(ac,bp);if(d3>=0&&d4<=d3)return b;let vc=d1*d4-d3*d2;if(vc<=0&&d1>=0&&d3<=0){let v=d1/(d1-d3);return MathLib.add(a,MathLib.mul(ab,v))}let cp=MathLib.sub(p,c),d5=MathLib.dot(ab,cp),d6=MathLib.dot(ac,cp);if(d6>=0&&d5<=d6)return c;let vb=d5*d2-d1*d6;if(vb<=0&&d2>=0&&d6<=0){let w=d2/(d2-d6);return MathLib.add(a,MathLib.mul(ac,w))}let va=d3*d6-d5*d4;if(va<=0&&(d4-d3)>=0&&(d5-d6)>=0){let w=(d4-d3)/((d4-d3)+(d5-d6));return MathLib.add(b,MathLib.mul(MathLib.sub(c,b),w))}let denom=1/(va+vb+vc),v=vb*denom,w=vc*denom;return MathLib.add(a,MathLib.add(MathLib.mul(ab,v),MathLib.mul(ac,w)))},
    rayTriangle:(origin,dir,a,b,c)=>{let e1=MathLib.sub(b,a),e2=MathLib.sub(c,a),h=MathLib.cross(dir,e2),det=MathLib.dot(e1,h);if(Math.abs(det)<MathLib.EPS)return null;let inv=1/det,s=MathLib.sub(origin,a),u=MathLib.dot(s,h)*inv;if(u<0||u>1)return null;let q=MathLib.cross(s,e1),v=MathLib.dot(dir,q)*inv;if(v<0||u+v>1)return null;let t=MathLib.dot(e2,q)*inv;return t>MathLib.EPS?t:null},
    polygonArea2D:points=>{let a=0;for(let i=0;i<points.length;i++){let p1=points[i],p2=points[(i+1)%points.length];a+=p1[0]*p2[1]-p2[0]*p1[1]}return Math.abs(a)*0.5},
    polygonCentroid2D:points=>{let x=0,z=0,a=0;for(let i=0;i<points.length;i++){let p1=points[i],p2=points[(i+1)%points.length],cross=p1[0]*p2[1]-p2[0]*p1[1];a+=cross;x+=(p1[0]+p2[0])*cross;z+=(p1[1]+p2[1])*cross}a*=0.5;if(Math.abs(a)<MathLib.EPS){let sx=0,sz=0;for(let i=0;i<points.length;i++){sx+=points[i][0];sz+=points[i][1]}return[sx/points.length,sz/points.length]}return[x/(6*a),z/(6*a)]},
    pointInPolygon2D:(p,points)=>{let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){let xi=points[i][0],zi=points[i][1],xj=points[j][0],zj=points[j][1];if((zi>p[1])!==(zj>p[1])&&p[0]<(xj-xi)*(p[1]-zi)/(zj-zi)+xi)inside=!inside}return inside},
    lineLineIntersect2D:(p1,p2,p3,p4)=>{let d1=[p2[0]-p1[0],p2[1]-p1[1]],d2=[p4[0]-p3[0],p4[1]-p3[1]],denom=d1[0]*d2[1]-d1[1]*d2[0];if(Math.abs(denom)<MathLib.EPS)return null;let d3=[p3[0]-p1[0],p3[1]-p1[1]],t=(d3[0]*d2[1]-d3[1]*d2[0])/denom,u=(d3[0]*d1[1]-d3[1]*d1[0])/denom;if(t<0||t>1||u<0||u>1)return null;return[p1[0]+d1[0]*t,p1[1]+d1[1]*t]},
    convexHull2D:points=>{let pts=points.slice().sort((a,b)=>a[0]===b[0]?a[1]-b[1]:a[0]-b[0]);if(pts.length<3)return pts;let cross=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]);let lower=[];for(let i=0;i<pts.length;i++){while(lower.length>=2&&cross(lower[lower.length-2],lower[lower.length-1],pts[i])<=0)lower.pop();lower.push(pts[i])}let upper=[];for(let i=pts.length-1;i>=0;i--){while(upper.length>=2&&cross(upper[upper.length-2],upper[upper.length-1],pts[i])<=0)upper.pop();upper.push(pts[i])}lower.pop();upper.pop();return lower.concat(upper)},
    triangulatePolygon2D:points=>{let idx=points.map((_,i)=>i),tris=[],cross=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]),signedArea=0;for(let i=0;i<points.length;i++){let p1=points[i],p2=points[(i+1)%points.length];signedArea+=p1[0]*p2[1]-p2[0]*p1[1]}if(signedArea<0)idx.reverse();let isEar=(a,b,c,remaining)=>{if(cross(points[a],points[b],points[c])<=0)return false;for(let i=0;i<remaining.length;i++){let pi=remaining[i];if(pi===a||pi===b||pi===c)continue;let bc=MathLibGeometry.barycentric([points[pi][0],0,points[pi][1]],[points[a][0],0,points[a][1]],[points[b][0],0,points[b][1]],[points[c][0],0,points[c][1]]);if(bc[0]>=-MathLib.EPS&&bc[1]>=-MathLib.EPS&&bc[2]>=-MathLib.EPS)return false}return true};let guard=0;while(idx.length>3&&guard<10000){guard++;let n=idx.length,earFound=false;for(let i=0;i<n;i++){let a=idx[(i-1+n)%n],b=idx[i],c=idx[(i+1)%n];if(isEar(a,b,c,idx)){tris.push([a,b,c]);idx.splice(i,1);earFound=true;break}}if(!earFound)break}if(idx.length===3)tris.push([idx[0],idx[1],idx[2]]);return tris},
    planeFromPoints:(a,b,c)=>({point:a,normal:MathLibGeometry.triangleNormal(a,b,c)}),
    signedDistanceToPlane:(p,planePoint,normal)=>MathLib.dot(MathLib.sub(p,planePoint),normal),
    projectPointOnPlane:(p,planePoint,normal)=>{let d=MathLibGeometry.signedDistanceToPlane(p,planePoint,normal);return MathLib.sub(p,MathLib.mul(normal,d))},
    planePlaneIntersect:(a,b)=>{let dir=MathLib.cross(a.normal,b.normal);if(MathLib.length2(dir)<MathLib.EPS)return null;dir=MathLib.normalize(dir);let n1=a.normal,n2=b.normal,d1=MathLib.dot(n1,a.point),d2=MathLib.dot(n2,b.point),n1n1=MathLib.dot(n1,n1),n1n2=MathLib.dot(n1,n2),n2n2=MathLib.dot(n2,n2),det=n1n1*n2n2-n1n2*n1n2;if(Math.abs(det)<MathLib.EPS)return null;let c1=(d1*n2n2-d2*n1n2)/det,c2=(d2*n1n1-d1*n1n2)/det,point=MathLib.add(MathLib.mul(n1,c1),MathLib.mul(n2,c2));return{point:point,direction:dir}},
    threePlaneIntersect:(a,b,c)=>{let m=[a.normal[0],a.normal[1],a.normal[2],b.normal[0],b.normal[1],b.normal[2],c.normal[0],c.normal[1],c.normal[2]],rhs=[MathLib.dot(a.normal,a.point),MathLib.dot(b.normal,b.point),MathLib.dot(c.normal,c.point)];return MathLibLinear.solve3(m,rhs)}
}
